sonar.projectKey=investigacion-accidentes
sonar.projectName=IST Investiga - Asistente de Accidentes
sonar.projectVersion=1.0
sonar.sources=arbol_causa_accidentes_ist
sonar.language=py
sonar.sourceEncoding=UTF-8
sonar.python.version=3.11
sonar.host.url=http://host.docker.internal:9000
sonar.token=sqa_220e5d86d12a9c55e8146494a987226d6ca1abf5

# Excluir migraciones, tests y vendor
sonar.exclusions=**/migrations/**,**/tests.py,**/static/**,**/templates/**,**/__pycache__/**,**/venv/**,**/.venv/**,**/.env,**/.env

# Tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.test.exclusions=**/tests.py
