# Generated by Django 5.2 on 2025-07-30 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accidentes',
            fields=[
                ('accidente_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_accidente', models.DateField(null=True)),
                ('hora_accidente', models.TimeField(null=True)),
                ('lugar_accidente', models.CharField(max_length=255, null=True)),
                ('tipo_accidente', models.CharField(choices=[('Golpe por', 'Golpe (golpeado) por'), ('Golpe con', 'Golpe (golpeado) con'), ('Golpe contra', 'Golpe (golpeado) contra'), ('Contacto con', 'Contacto con'), ('Contacto por', 'Contacto por'), ('Caída mismo nivel', 'Caída al mismo nivel'), ('Caída distinto nivel', 'Caída a distinto nivel'), ('Atrapamiento', 'Atrapamiento'), ('Aprisionamiento', 'Aprisionamiento'), ('Sobreesfuerzo', 'Sobreesfuerzo'), ('Exposición a', 'Exposición a')], max_length=100, null=True)),
                ('naturaleza_lesion', models.CharField(max_length=255, null=True)),
                ('parte_afectada', models.CharField(max_length=255, null=True)),
                ('tarea', models.CharField(max_length=255, null=True)),
                ('operacion', models.CharField(max_length=255, null=True)),
                ('danos_personas', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2, null=True)),
                ('danos_propiedad', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2, null=True)),
                ('perdidas_proceso', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2, null=True)),
                ('contexto', models.TextField(null=True)),
                ('circunstancias', models.TextField(null=True)),
                ('preinitial_story', models.TextField(null=True)),
                ('preguntas_entrevista', models.TextField(null=True)),
                ('resumen', models.TextField(null=True)),
                ('relato', models.TextField(null=True)),
                ('codigo_accidente', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'accidentes',
            },
        ),
        migrations.CreateModel(
            name='CentrosTrabajo',
            fields=[
                ('centro_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_local', models.CharField(max_length=255)),
                ('direccion_centro', models.CharField(max_length=255, null=True)),
                ('region', models.CharField(max_length=100, null=True)),
                ('comuna', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'centros_trabajo',
            },
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('empresa_id', models.AutoField(primary_key=True, serialize=False)),
                ('empresa_sel', models.CharField(max_length=255)),
                ('rut_empresa', models.CharField(max_length=20, unique=True)),
                ('actividad', models.CharField(max_length=255, null=True)),
                ('direccion_empresa', models.CharField(max_length=255, null=True)),
                ('telefono', models.CharField(max_length=30, null=True)),
                ('representante_legal', models.CharField(max_length=255, null=True)),
                ('region', models.CharField(max_length=100, null=True)),
                ('comuna', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'empresas',
            },
        ),
        migrations.CreateModel(
            name='Holdings',
            fields=[
                ('holding_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'holdings',
            },
        ),
        migrations.CreateModel(
            name='AccidenteJsonData',
            fields=[
                ('accidente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accidentes.accidentes')),
                ('preguntas_json', models.JSONField()),
                ('otro_json_1', models.JSONField(null=True)),
                ('otro_json_2', models.JSONField(null=True)),
            ],
            options={
                'db_table': 'accidente_json_data',
            },
        ),
        migrations.AddField(
            model_name='accidentes',
            name='centro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accidentes', to='accidentes.centrostrabajo'),
        ),
        migrations.CreateModel(
            name='Declaraciones',
            fields=[
                ('declaracion_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_decl', models.CharField(choices=[('accidentado', 'Accidentado'), ('testigo', 'Testigo')], default='testigo', max_length=20)),
                ('nombre', models.CharField(max_length=255, null=True)),
                ('rut', models.CharField(max_length=20, null=True)),
                ('cargo', models.CharField(max_length=255, null=True)),
                ('texto', models.TextField(null=True)),
                ('accidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accidentes.accidentes')),
            ],
            options={
                'db_table': 'declaraciones',
            },
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('documento_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('documento', models.CharField(max_length=255, null=True)),
                ('objetivo', models.TextField(null=True)),
                ('nombre_archivo', models.CharField(max_length=255, null=True)),
                ('mime_type', models.CharField(max_length=100, null=True)),
                ('contenido', models.BinaryField(null=True)),
                ('subido_el', models.DateTimeField(auto_now_add=True)),
                ('url', models.CharField(max_length=2048, null=True)),
                ('accidente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accidentes.accidentes')),
            ],
            options={
                'db_table': 'documentos',
            },
        ),
        migrations.AddField(
            model_name='centrostrabajo',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accidentes.empresas'),
        ),
        migrations.CreateModel(
            name='Hechos',
            fields=[
                ('hecho_id', models.AutoField(primary_key=True, serialize=False)),
                ('secuencia', models.SmallIntegerField(null=True)),
                ('descripcion', models.TextField(null=True)),
                ('accidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accidentes.accidentes')),
            ],
            options={
                'db_table': 'hechos',
            },
        ),
        migrations.AddField(
            model_name='empresas',
            name='holding',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accidentes.holdings'),
        ),
        migrations.CreateModel(
            name='Prescripciones',
            fields=[
                ('prescripcion_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100, null=True)),
                ('prioridad', models.CharField(max_length=50, null=True)),
                ('plazo', models.DateField(null=True)),
                ('responsable', models.CharField(max_length=255, null=True)),
                ('descripcion', models.TextField(null=True)),
                ('accidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accidentes.accidentes')),
            ],
            options={
                'db_table': 'prescripciones',
            },
        ),
        migrations.CreateModel(
            name='Trabajadores',
            fields=[
                ('trabajador_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_trabajador', models.CharField(max_length=255, null=True)),
                ('rut_trabajador', models.CharField(max_length=20, null=True, unique=True)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('nacionalidad', models.CharField(choices=[('Chilena', 'Chilena'), ('Peruana', 'Peruana'), ('Venezolana', 'Venezolana'), ('Boliviana', 'Boliviana'), ('Argentina', 'Argentina'), ('Colombiana', 'Colombiana'), ('Ecuatoriana', 'Ecuatoriana'), ('Haitiana', 'Haitiana'), ('Paraguaya', 'Paraguaya'), ('Uruguaya', 'Uruguaya')], max_length=100, null=True)),
                ('estado_civil', models.CharField(choices=[('Soltero/a', 'Soltero/a'), ('Casado/a', 'Casado/a'), ('Viudo/a', 'Viudo/a'), ('Divorciado/a', 'Divorciado/a')], max_length=50, null=True)),
                ('domicilio', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('antiguedad_empresa', models.CharField(max_length=100, null=True)),
                ('antiguedad_cargo', models.CharField(max_length=100, null=True)),
                ('cargo_trabajador', models.CharField(max_length=100, null=True)),
                ('contrato', models.CharField(choices=[('Indefinido', 'Indefinido'), ('Plazo Fijo', 'Plazo Fijo'), ('Honorarios', 'Honorarios'), ('Contratista', 'Contratista')], max_length=50, null=True)),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accidentes.empresas')),
            ],
            options={
                'db_table': 'trabajadores',
            },
        ),
        migrations.AddField(
            model_name='accidentes',
            name='trabajador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accidentes', to='accidentes.trabajadores'),
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('apepat', models.CharField(max_length=100, null=True)),
                ('apemat', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=254, unique=True)),
                ('pass_field', models.CharField(db_column='pass', max_length=255)),
                ('tipo', models.IntegerField()),
                ('Cargo', models.CharField(max_length=100, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accidentes.empresas')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.AddField(
            model_name='accidentes',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accidentes', to='accidentes.usuarios'),
        ),
        migrations.CreateModel(
            name='ArbolCausas',
            fields=[
                ('arbol_id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.SmallIntegerField()),
                ('is_current', models.BooleanField(default=False)),
                ('arbol_json_5q', models.TextField(null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('arbol_json_dot', models.TextField(null=True)),
                ('accidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accidentes.accidentes')),
            ],
            options={
                'db_table': 'arbol_causas',
                'unique_together': {('accidente', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Informes',
            fields=[
                ('informe_id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.SmallIntegerField()),
                ('is_current', models.BooleanField(default=False)),
                ('codigo', models.CharField(max_length=50, null=True)),
                ('fecha_informe', models.DateField(null=True)),
                ('investigador', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accidentes.accidentes')),
            ],
            options={
                'db_table': 'informes',
                'unique_together': {('accidente', 'version')},
            },
        ),
        migrations.CreateModel(
            name='PreguntasGuia',
            fields=[
                ('pregunta_id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(max_length=36)),
                ('categoria', models.CharField(choices=[('accidentado', 'Accidentado'), ('testigos', 'Testigos'), ('supervisores', 'Supervisores')], max_length=20)),
                ('pregunta', models.TextField(null=True)),
                ('objetivo', models.TextField(null=True)),
                ('respuesta', models.TextField(null=True)),
                ('accidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accidentes.accidentes')),
            ],
            options={
                'db_table': 'preguntas_guia',
                'unique_together': {('accidente', 'uuid')},
            },
        ),
        migrations.AddIndex(
            model_name='accidentes',
            index=models.Index(fields=['codigo_accidente'], name='accidentes_codigo__31c074_idx'),
        ),
    ]
