# Generated by Django 5.2 on 2025-07-30 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accidentes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accidentes',
            name='preguntas_entrevista',
        ),
        migrations.RemoveField(
            model_name='accidentes',
            name='preinitial_story',
        ),
        migrations.RemoveField(
            model_name='accidentes',
            name='relato',
        ),
        migrations.RemoveField(
            model_name='accidentes',
            name='resumen',
        ),
    ]
