# Generated by Django 5.2 on 2025-08-04 21:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidentes', '0002_remove_accidentes_preguntas_entrevista_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos',
            name='contenido',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='url',
            field=models.CharField(help_text='Enlace externo o URL interna de descarga', max_length=2048, null=True),
        ),
        migrations.CreateModel(
            name='Relato',
            fields=[
                ('relato_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relato_inicial', models.TextField(blank=True, null=True)),
                ('pregunta_1', models.TextField(blank=True, null=True)),
                ('respuesta_1', models.TextField(blank=True, null=True)),
                ('pregunta_2', models.TextField(blank=True, null=True)),
                ('respuesta_2', models.TextField(blank=True, null=True)),
                ('pregunta_3', models.TextField(blank=True, null=True)),
                ('respuesta_3', models.TextField(blank=True, null=True)),
                ('relato_final', models.TextField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('accidente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relato', to='accidentes.accidentes')),
            ],
        ),
    ]
