# Generated by Django 5.2 on 2025-08-04 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accidentes', '0003_alter_documentos_contenido_alter_documentos_url_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='relato',
            table='accidentes_relato',
        ),
    ]
