# Generated by Django 5.2 on 2025-08-04 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidentes', '0004_alter_relato_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaraciones',
            name='accidente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declaraciones', to='accidentes.accidentes'),
        ),
    ]
