# Generated by Django 5.2 on 2025-08-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidentes', '0005_alter_declaraciones_accidente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaraciones',
            name='tipo_decl',
            field=models.CharField(choices=[('accidentado', 'Accidentado'), ('testigo', 'Testigo'), ('supervisor', 'Supervisor')], default='testigo', max_length=20),
        ),
    ]
