# Generated by Django 5.2 on 2025-08-05 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidentes', '0006_alter_declaraciones_tipo_decl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relato',
            name='accidente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relato', to='accidentes.accidentes'),
        ),
    ]
