# Generated by Django 5.2 on 2025-08-18 14:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidentes', '0007_alter_relato_accidente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accidentes',
            options={'ordering': ['-fecha_accidente', '-hora_accidente', '-accidente_id']},
        ),
        migrations.RemoveField(
            model_name='accidentes',
            name='usuario',
        ),
        migrations.AddField(
            model_name='accidentes',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='accidentes',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accidentes_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accidentes',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accidentes',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accidentes_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accidentes',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accidentes', to='accidentes.empresas'),
        ),
        migrations.AddField(
            model_name='accidentes',
            name='holding',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accidentes', to='accidentes.holdings'),
        ),
        migrations.AddField(
            model_name='accidentes',
            name='usuario_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accidentes_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='holding',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas', to='accidentes.holdings'),
        ),
        migrations.AddIndex(
            model_name='accidentes',
            index=models.Index(fields=['holding', 'empresa'], name='accidentes_holding_45afb3_idx'),
        ),
        migrations.AddIndex(
            model_name='empresas',
            index=models.Index(fields=['rut_empresa'], name='empresas_rut_emp_3e1506_idx'),
        ),
        migrations.AddIndex(
            model_name='empresas',
            index=models.Index(fields=['holding', 'empresa_sel'], name='empresas_holding_f1224b_idx'),
        ),
    ]
