# Generated by Django 5.2 on 2025-08-25 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidentes', '0008_alter_accidentes_options_remove_accidentes_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidentes',
            name='circunstancias',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentes',
            name='contexto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentes',
            name='danos_personas',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='accidentes',
            name='danos_propiedad',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='accidentes',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accidentes', to='accidentes.empresas'),
        ),
        migrations.AlterField(
            model_name='accidentes',
            name='hora_accidente',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accidentes',
            name='lugar_accidente',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='accidentes',
            name='naturaleza_lesion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='accidentes',
            name='operacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='accidentes',
            name='parte_afectada',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='accidentes',
            name='perdidas_proceso',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='accidentes',
            name='tarea',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='accidentes',
            name='tipo_accidente',
            field=models.CharField(blank=True, choices=[('Golpe por', 'Golpe (golpeado) por'), ('Golpe con', 'Golpe (golpeado) con'), ('Golpe contra', 'Golpe (golpeado) contra'), ('Contacto con', 'Contacto con'), ('Contacto por', 'Contacto por'), ('Caída mismo nivel', 'Caída al mismo nivel'), ('Caída distinto nivel', 'Caída a distinto nivel'), ('Atrapamiento', 'Atrapamiento'), ('Aprisionamiento', 'Aprisionamiento'), ('Sobreesfuerzo', 'Sobreesfuerzo'), ('Exposición a', 'Exposición a')], max_length=100, null=True),
        ),
    ]
