# Generated by Django 5.2 on 2025-08-25 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidentes', '0009_alter_accidentes_circunstancias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidentes',
            name='centro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accidentes', to='accidentes.centrostrabajo'),
        ),
        migrations.AlterField(
            model_name='accidentes',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accidentes', to='accidentes.empresas'),
        ),
    ]
