# Generated by Django 5.2 on 2025-09-02 18:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidentes', '0010_alter_accidentes_centro_alter_accidentes_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajadores',
            name='antiguedad_cargo',
        ),
        migrations.RemoveField(
            model_name='trabajadores',
            name='antiguedad_empresa',
        ),
        migrations.AddField(
            model_name='trabajadores',
            name='antiguedad_cargo_anios',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trabajadores',
            name='antiguedad_cargo_meses',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(11)]),
        ),
        migrations.AddField(
            model_name='trabajadores',
            name='antiguedad_empresa_anios',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trabajadores',
            name='antiguedad_empresa_meses',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(11)]),
        ),
        migrations.AddField(
            model_name='trabajadores',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True),
        ),
    ]
