# Generated by Django 5.2 on 2025-09-16 12:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidentes', '0011_remove_trabajadores_antiguedad_cargo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPrivacyConsent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ley_numero', models.CharField(choices=[('21.459', 'Ley 21.459 - Delitos Informáticos'), ('21.663', 'Ley 21.663 - Ley Marco de Ciberseguridad'), ('21.719', 'Ley 21.719 - Protección de Datos Personales')], max_length=10)),
                ('version', models.CharField(default='v1.0', max_length=50)),
                ('aceptado_en', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_privacy_consents',
                'indexes': [models.Index(fields=['usuario', 'ley_numero'], name='user_privac_usuario_56c405_idx'), models.Index(fields=['aceptado_en'], name='user_privac_aceptad_5522fd_idx')],
                'unique_together': {('usuario', 'ley_numero', 'version')},
            },
        ),
    ]
