# Generated by Django 5.2 on 2025-09-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidentes', '0012_relato_fraseqr1_relato_fraseqr2_relato_fraseqr3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relato',
            name='fraseQR1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relato',
            name='fraseQR2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relato',
            name='fraseQR3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
