# Generated by Django 5.2 on 2025-10-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidentes', '0013_relato_fraseqr1_relato_fraseqr2_relato_fraseqr3'),
    ]

    operations = [
        migrations.AddField(
            model_name='accidentes',
            name='resumen',
            field=models.CharField(blank=True, help_text='Resumen breve del accidente (máx. 1000 caracteres).', max_length=1000, null=True, verbose_name='Resumen'),
        ),
    ]
