"""
Django settings for arbol_causa_accidentes_ist project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from dotenv import load_dotenv
from pathlib import Path
from decouple import Config, RepositoryEnv
from django.urls import reverse_lazy


load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env_path = BASE_DIR / '.env'
config = Config(repository=RepositoryEnv(env_path))
# Cargar claves desde .env
OPENAI_API_KEY = config("OPENAI_API_KEY")
DEEPSEEK_API_KEY = config("DEEPSEEK_API_KEY")
DEFAULT_MODEL = config("DEFAULT_MODEL", default="gpt-4")
FALLBACK_MODEL = config("FALLBACK_MODEL", default="gpt-3.5-turbo")
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-f5em2y_8!!w*b_%9bb_6eq&n3qv7^f0-t6jyf)j=i^1jf=qfpo"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

IA_LOG_PROMPTS = True

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {"console": {"class": "logging.StreamHandler"}},
    "loggers": {
        "accounts.forms":        {"handlers": ["console"], "level": "INFO", "propagate": False},
        "core.email_backends":   {"handlers": ["console"], "level": "INFO", "propagate": False},
        "core.services.apiemail":{"handlers": ["console"], "level": "INFO", "propagate": False},
        "core.utils.token":      {"handlers": ["console"], "level": "INFO", "propagate": False},
    },
    "root": {"handlers": ["console"], "level": "INFO"},
}


ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = [
    "http://localhost", # REMOVE ON PROD
    "http://20.106.186.24", # REMOVE ON PROD
    "http://10.11.23.35:5085", # REMOVE ON PROD
    "http://10.11.23.23:5085", # REMOVE ON PROD
    "http://10.11.20.89" # REMOVE ON PROD 
]

USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'http')

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "accidentes.apps.AccidentesConfig",
    "widget_tweaks",
    "adminpanel",
    "import_export",
    "accounts.apps.AccountsConfig"
]

AUTHENTICATION_BACKENDS = [
    "accounts.backends.RutOnlyBackend",
]

AUTH_USER_MODEL = "accounts.User"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "accounts.middleware.ForcePasswordChangeMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_htmx.middleware.HtmxMiddleware"
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "accidentes.context_processor.accidente_nav_context",
                "accidentes.context_processor.breadcrumbs",      # <- tu CP existente (archivo singular)
                "accidentes.context_processors.case_progress",   # <- NUEVO (archivo plural)
            ],
        },
    },
]


WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DB_ENGINE   = os.getenv('DB_ENGINE'   , None)
DB_USERNAME = os.getenv('DB_USERNAME' , None)
DB_PASS     = os.getenv('DB_PASS'     , None)
DB_HOST     = os.getenv('DB_HOST'     , None)
DB_PORT     = os.getenv('DB_PORT'     , None)
DB_NAME     = os.getenv('DB_NAME'     , None)

# Lógica de base de datos
if (AMBIENTE := os.getenv("AMBIENTE", "produccion").lower()) == "desarrollo":
    print("🔧 Modo desarrollo: usando SQLite")
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': 'db.sqlite3',
        }
    }
else:
    print("🚀 Modo producción: usando base de datos externa")
    DATABASES = {
        'default': {
            'ENGINE'  : 'django.db.backends.' + DB_ENGINE,
            'NAME'    : DB_NAME,
            'USER'    : DB_USERNAME,
            'PASSWORD': DB_PASS,
            'HOST'    : DB_HOST,
            'PORT'    : DB_PORT,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "es-CL"

TIME_ZONE = "America/Santiago"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [BASE_DIR / 'static']

# LOGIN
LOGIN_URL = reverse_lazy("accounts:login")               # en vez de string "hardcoded"
LOGIN_REDIRECT_URL = reverse_lazy("accidentes:home")
LOGOUT_REDIRECT_URL = reverse_lazy("accounts:login")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Session settings
# Use database-backed sessions for persistence across requests
SESSION_ENGINE = 'django.contrib.sessions.backends.db'


#Prtected media to serve file through nginx
PROTECTED_MEDIA_ROOT = BASE_DIR / "protected_media"
PROTECTED_MEDIA_URL = "/protected_media/"

# Config credenciales de API
API_ACCESS = {
    "API_EMAIL": {
        "CLIENT"        : os.getenv("API_EMAIL_CLIENT"),
        "SECRET"        : os.getenv("API_EMAIL_SECRET"),
        "BASE_URL"      : os.getenv("API_EMAIL_BASE_URL", "https://apiemail.ist.cl/api/"),  # debe terminar con '/'
        "TOKEN_ENDPOINT": os.getenv("API_EMAIL_TOKEN_ENDPOINT", "oauth/token"),
        "TTL"           : int(os.getenv("API_EMAIL_TTL", "3600")),  # <-- fix cast
    }
}

# Datos del remitente
IST_EMAIL_ACTOR       = os.getenv("IST_EMAIL_ACTOR", "agustin.lepe@ist.cl")  # costumerLoadEmail (quién ejecuta)
IST_EMAIL_FROM_NAME   = os.getenv("IST_EMAIL_FROM_NAME", "Asistente de Investigación de Accidentes")
IST_EMAIL_FROM_EMAIL  = os.getenv("IST_EMAIL_FROM_EMAIL", IST_EMAIL_ACTOR)  # <-- opcional, si quieres separar
IST_EMAIL_SOURCE_IP   = os.getenv("IST_EMAIL_SOURCE_IP", "")

# Email de Django (coherencia global)
DEFAULT_FROM_EMAIL    = os.getenv("DEFAULT_FROM_EMAIL", "no-reply@ist.cl")

# Backend personalizado para envío de emails
EMAIL_BACKEND = "core.email_backends.ist_via_token.EmailBackend"

