FROM python:3.11

WORKDIR /usr/src/app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY requirements.txt .

RUN apt-get update -yqq && apt-get install -yqq iputils-ping && apt-get install -y graphviz

RUN ln -fs /usr/share/zoneinfo/America/Santiago /etc/localtime
RUN dpkg-reconfigure -f noninteractive tzdata

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

COPY entrypoint.sh /app/entrypoint.sh
RUN sed -i 's/\r$//' /app/entrypoint.sh && chmod +x /app/entrypoint.sh 
# Migrations podrían ejecutarse desde entrypoint.sh si prefieres control
# RUN python manage.py makemigrations
# RUN python manage.py migrate
ENTRYPOINT ["/app/entrypoint.sh"]
CMD gunicorn --config gunicorn-cfg.py core.wsgi