# Generated by Django 5.2 on 2025-08-16 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('admin', 'Admin Global'), ('admin_ist', 'Admin IST'), ('admin_holding', 'Admin Holding'), ('admin_empresa', 'Admin Empresa'), ('coordinador', 'Coordinador'), ('investigador', 'Investigador')], default='investigador', max_length=15),
        ),
    ]
