# Generated by Django 5.2 on 2025-08-18 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('admin', 'Admin Global'), ('admin_ist', 'Admin IST'), ('admin_holding', 'Admin Holding'), ('admin_empresa', 'Admin Empresa'), ('coordinador', 'Coordinador'), ('investigador', 'Investigador'), ('investigador_ist', 'Investigador IST')], default='investigador', max_length=35),
        ),
    ]
